###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

wizzle-mailhog:
  image: mailhog/mailhog:latest
  container_name: wizzle-mailhog
  ports:
    - "8125:8025"

wizzle-mysql:
  image: mysql:5.7
  container_name: wizzle-mysql
  volumes:
      - ../mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

wizzle-nginx:
  image: nginx:latest
  container_name: wizzle-nginx
  volumes:
      - ./cakephp:/var/www/cakephp
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8180:80"
  links:
   - wizzle-php-fpm

wizzle-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: wizzle-php-fpm
  volumes:
    - ./cakephp:/var/www/cakephp
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - wizzle-mailhog
    - wizzle-mysql
